### ISSUE TITLE
installation  failed 

### ISSUE THREAD

**Issue by santoshMareddy** [throb/vfxpipe#8]
// Error: IOError: file D:\CG_Apps\Plugins\vfxpipe_master\python\fxpipe\__init__.py line 16: 2 //
am getting this error after installation

**Comment by throb** [comment]
Please give me more details on the error.
Thanks!

**Comment by santoshMareddy** [comment]
please connect me on team viewer so that you  you can understand

**Comment by santoshMareddy** [comment]
id: 1 147 678 514

password : tf467q

**Comment by throb** [comment]
just send the full dump from a command line and that will help

**Comment by santoshMareddy** [comment]
![debug](https://user-images.githubusercontent.com/21692853/50544556-67698980-0c1f-11e9-8d7f-d62560071fc7.png)

**Comment by santoshMareddy** [comment]
please help with installation bro

**Comment by santoshMareddy** [comment]
Working perfectly
